### PR TITLE
fix css escaping  in postcss-has-pseudo

### PR DESCRIPTION
**Pull request by romainmenke**
Used to mix `encodeURIComponent` with regex to decode partially after encoding and then encoding again differently with regex.

Now goes through the value once and encodes each piece correctly from the start.

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
@romainmenke this looks good to me and I guess it'd be hard but is there any chance we can get a test?

**Comment by romainmenke** [comment]
@Antonio-Laguna The new code now correctly handles escape sequences already present in selectors :

input :

```css
:has(.esc\:aped) {
	order: 7;
}
```

previous output :

This was handled as if `:` indicated a pseudo.

```css
[\:has\(.esc\%5C\:aped\)] {
	order: 7;
}
```

new output :

Here `\:` is handled as an escaped `:` and part of the `.esca:ped` class name.

```css
[\:has\(.esc\%5C\%3Aaped\)] {
	order: 7;
}
```

**Comment by Antonio-Laguna** [comment]
Thanks! That's perfect!

**Review by Antonio-Laguna — APPROVED** [review]
LGTM

**Pull request merged**
