### PR TITLE
fix postcss 8.2.x compat

### PR DESCRIPTION
**Pull request by romainmenke**
We do not support PostCSS v8.2.5 any more but as some have this version pinned by tools we can do a minimal effort to help them out.

### CODE REVIEW

**Review by Antonio-Laguna — APPROVED** [review]
This LGTM.

IMHO we should add links to #147 

Furthermore, I'm inclined to point to vercel/next.js/issues/33135 for a couple of reasons:

- So it's obvious we're fixing a Next.js issue.
- Easier navigation

Let me know your thoughts here.

**Comment by romainmenke** [comment]
I was hesitant to point to one individual tool repackager as there are so many these days.
I bet more are doing it wrong or less than ideal.

Even if I have strong personal opinions about this trend it is however the reality of frontend development today. Keeping it vague might be more productive in the long run :)

**Comment by Antonio-Laguna** [comment]
It's not a finger pointing thing IMHO but rather relating these two tools and one issue, Tomorrow could be Tailwind 😂

Won't enforce it though so will leave it up to you. 

Thoughts on linking the original issue though?

**Comment by romainmenke** [comment]
Hehe, tailwind actually does this correctly.

https://github.com/tailwindlabs/tailwindcss/blob/62569092e7ba79fc45f77451c179b3f6cc0f80f8/package.json#L64

I have added the link to the original issue in the changelog.
Indeed a good addition to track this change back in the future!

**Pull request merged**
