### PR TITLE
Update README.md: consistent indentation

### PR DESCRIPTION
**Pull request by caldwell-63**
Makes indentation consistent across the entire file

### CODE REVIEW

**Comment by romainmenke** [comment]
Hi @igorbabko
Thank you for your contribution!

Can you elaborate a bit on what you are trying to solve?

For context, these examples are actual output from the plugin and the plugin doesn't alter indents.

Why did you also change indents to spaces?

**Comment by romainmenke** [comment]
Closing because this is an unwanted change.

Feel free open an issue to discuss any problems you might be trying to solve here :)

**Comment by caldwell-63** [comment]
8-width tabs in readme look absolutely horrendous, therefore this pull request

**Comment by romainmenke** [comment]
Hi @caldwell-63 

We always tabs exactly because anyone can configure their preferred tab size.
If yours has a width of 8 then it is because you are using a default or have set it to have a width of 8.

For GitHub you can find more info here: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference#

We will never go back to spaces :)

**Pull request closed without merging**
